apiVersion: v1
kind: Pod
metadata:
  name: network-stranger
  namespace: lab
  labels:
    app: network-stranger
    access: backend-denied
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.12.1
      imagePullPolicy: IfNotPresent

      command:
        - sleep
        - infinity

      resources:
        requests:
          cpu: 10m
          memory: 16Mi

        limits:
          cpu: 50m
          memory: 64Mi