apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
  namespace: lab
data:
  APP_NAME: "hello-api"
  APP_ENV: "dev"
  LOG_LEVEL: "debug"
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            return 200 "Hello from ConfigMap nginx config\n";
        }
    }