apiVersion: v1
kind: Pod
metadata:
  name: rbac-test-pod
  namespace: lab
  labels:
    app: rbac-test
spec:
  serviceAccountName: demo-reader
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - sleep
        - "3600"