apiVersion: v1
kind: Namespace
metadata:
  name: lab

---
apiVersion: v1
kind: Namespace
metadata:
  name: observability

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx