apiVersion: v1
kind: Service
metadata:
  name: hello-probes-service
  namespace: lab
  labels:
    app: hello-probes
spec:
  type: ClusterIP
  selector:
    app: hello-probes
  ports:
    - name: http
      port: 80
      targetPort: 80